export const countryCodes = [
  { code: "GH", name: "Ghana" },
  { code: "GA", name: "Gabon" },
  { code: "GY", name: "Guyana" },
  { code: "GM", name: "Gambia" },
  { code: "GG", name: "Guernsey" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GT", name: "Guatemala" },
  { code: "GU", name: "Guam" },
  { code: "GD", name: "Grenada" },
  { code: "GR", name: "Ελλάς" },
  { code: "GL", name: "Greenland" },
  { code: "GN", name: "Guinée" },
  { code: "GW", name: "Guiné-Bissau" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Naoero" },
  { code: "NG", name: "Nigeria" },
  { code: "AQ", name: "Antarctica" },
  { code: "SS", name: "South Sudan" },
  { code: "ZA", name: "South Africa" },
  { code: "NL", name: "Nederland" },
  { code: "AN", name: "Netherlands Antilles" },
  { code: "NP", name: "नेपाल" },
  { code: "NO", name: "Norge" },
  { code: "NF", name: "Norfolk Island" },
  { code: "NC", name: "New Caledonia" },
  { code: "NZ", name: "New Zealand" },
  { code: "NU", name: "Niue" },
  { code: "NE", name: "Niger" },
  { code: "NI", name: "Nicaragua" },
  { code: "KR", name: "한국" },
  { code: "DK", name: "Danmark" },
  { code: "DO", name: "Dominican Republic" },
  { code: "DM", name: "Dominica" },
  { code: "DE", name: "Deutschland" },
  { code: "TL", name: "Timor-Leste" },
  { code: "LA", name: "ນລາວ" },
  { code: "LR", name: "Liberia" },
  { code: "LV", name: "Latvija" },
  { code: "RU", name: "Россия" },
  { code: "LB", name: "لبنان" },
  { code: "LS", name: "Lesotho" },
  { code: "RE", name: "Reunion" },
  { code: "RO", name: "România" },
  { code: "LU", name: "Lëtzebuerg" },
  { code: "RW", name: "Rwanda" },
  { code: "LY", name: "ليبيا" },
  { code: "LT", name: "Lietuva" },
  { code: "LI", name: "Liechtenstein" },
  { code: "MG", name: "Madagasikara" },
  { code: "MQ", name: "Martinique" },
  { code: "MH", name: "Marshall Islands" },
  { code: "YT", name: "Mayotte" },
  { code: "MO", name: "Macao" },
  { code: "MK", name: "Македонија" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "ML", name: "Mali" },
  { code: "IM", name: "Isle of Man" },
  { code: "MX", name: "México" },
  { code: "MC", name: "Monaco" },
  { code: "MA", name: "المغرب" },
  { code: "MU", name: "Mauritius" },
  { code: "MR", name: "موريتانيا" },
  { code: "MZ", name: "Moçambique" },
  { code: "ME", name: "Црна Гора" },
  { code: "MS", name: "Montserrat" },
  { code: "MD", name: "Moldova" },
  { code: "MV", name: "ގުޖޭއްރާ ޔާއްރިހޫމްޖ" },
  { code: "MT", name: "Malta" },
  { code: "MN", name: "Монгол Улс" },
  { code: "US", name: "United States" },
  { code: "UM", name: "United States minor outlying islands" },
  { code: "VI", name: "Virgin Islands, U.S." },
  { code: "MM", name: "Myanmar(Burma)" },
  { code: "FM", name: "Micronesia" },
  { code: "VU", name: "Vanuatu" },
  { code: "BH", name: "البحرين" },
  { code: "BB", name: "Barbados" },
  { code: "VA", name: "Città del Vaticano" },
  { code: "BS", name: "Bahamas" },
  { code: "BD", name: "বাংলাদেশ" },
  { code: "BM", name: "Bermuda" },
  { code: "BJ", name: "Bénin" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Việt Nam" },
  { code: "BE", name: "België" },
  { code: "BY", name: "Белару́сь" },
  { code: "BZ", name: "Belize" },
  { code: "BA", name: "Bosna i Hercegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BO", name: "Bolivia" },
  { code: "BI", name: "Uburundi" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BV", name: "Bouvet Island" },
  { code: "BT", name: "འབྲུག་ཡུལ" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "BG", name: "България" },
  { code: "BR", name: "Brasil" },
  { code: "BN", name: "Brunei Darussalam" },
  { code: "WS", name: "Samoa" },
  { code: "SA", name: "المملكة العربية السعودية" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "São Tomé and Príncipe" },
  { code: "PM", name: "Saint Pierre and Miquelon" },
  { code: "EH", name: "الصحراء الغربية" },
  { code: "SN", name: "Sénégal" },
  { code: "RS", name: "Србија" },
  { code: "SC", name: "Seychelles" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "SH", name: "Saint Helena" },
  { code: "SO", name: "Soomaaliya" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SD", name: "السودان" },
  { code: "SR", name: "Suriname" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SJ", name: "Svalbard and Jan Mayen" },
  { code: "SZ", name: "Swaziland" },
  { code: "SE", name: "Sverige" },
  { code: "CH", name: "Schweiz" },
  { code: "ES", name: "España" },
  { code: "SK", name: "Slovensko" },
  { code: "SI", name: "Slovenija" },
  { code: "SY", name: "سوريا" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapura" },
  { code: "AE", name: "الإمارات العربيّة المتّحدة" },
  { code: "AW", name: "Aruba" },
  { code: "AM", name: "Հայաստան" },
  { code: "AR", name: "Argentina" },
  { code: "AS", name: "American Samoa" },
  { code: "IS", name: "Ísland" },
  { code: "HT", name: "Haïti" },
  { code: "IE", name: "Ireland" },
  { code: "AZ", name: "Azərbaycan" },
  { code: "AF", name: "افغانستان" },
  { code: "AD", name: "Andorra" },
  { code: "AL", name: "Shqipëria" },
  { code: "DZ", name: "الجزائر" },
  { code: "AO", name: "Angola" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AI", name: "Anguilla" },
  { code: "ER", name: "Ertra" },
  { code: "EE", name: "Eesti" },
  { code: "EC", name: "Ecuador" },
  { code: "ET", name: "Ityop'iya" },
  { code: "SV", name: "El Salvador" },
  { code: "GB", name: "United Kingdom" },
  { code: "VG", name: "Virgin Islands, British" },
  { code: "IO", name: "British Indian Ocean Territory" },
  { code: "YE", name: "اليمن" },
  { code: "OM", name: "عمان" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Österreich" },
  { code: "HN", name: "Honduras" },
  { code: "AX", name: "Aland Islands" },
  { code: "WF", name: "Wallis and Futuna" },
  { code: "JO", name: "الاردن" },
  { code: "UG", name: "Uganda" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "O'zbekiston" },
  { code: "UA", name: "Україна" },
  { code: "IQ", name: "العراق" },
  { code: "IR", name: "ایران" },
  { code: "IL", name: "ישראל" },
  { code: "EG", name: "مصر" },
  { code: "IT", name: "Italia" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "JP", name: "日本" },
  { code: "JM", name: "Jamaica" },
  { code: "ZM", name: "Zambia" },
  { code: "JE", name: "Jersey" },
  { code: "GQ", name: "Guinea Ecuatorial" },
  { code: "KP", name: "조선" },
  { code: "GE", name: "საქართველო" },
  { code: "CF", name: "République Centrafricaine" },
  { code: "TW", name: "台灣" },
  { code: "CN", name: "中国" },
  { code: "DJ", name: "Djibouti" },
  { code: "GI", name: "Gibraltar" },
  { code: "ZW", name: "Zimbabwe" },
  { code: "TD", name: "Tchad" },
  { code: "CZ", name: "Česko" },
  { code: "CL", name: "Chile" },
  { code: "CM", name: "Cameroun" },
  { code: "CV", name: "Cabo Verde" },
  { code: "KZ", name: "Қазақстан" },
  { code: "QA", name: "قطر" },
  { code: "KH", name: "Kampuchea" },
  { code: "CA", name: "Canada" },
  { code: "KE", name: "Kenya" },
  { code: "KY", name: "Cayman Islands" },
  { code: "KM", name: "Comores" },
  { code: "CR", name: "Costa Rica" },
  { code: "CC", name: "Cocos Islands" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "CO", name: "Colombia" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo, Democratic Republic of the" },
  { code: "CU", name: "Cuba" },
  { code: "KW", name: "الكويت" },
  { code: "CK", name: "Cook Islands" },
  { code: "HR", name: "Hrvatska" },
  { code: "CX", name: "Christmas Island" },
  { code: "KG", name: "Кыргызстан" },
  { code: "KI", name: "Kiribati" },
  { code: "CY", name: "Κυπρος" },
  { code: "TH", name: "ราชอาณาจักรไทย" },
  { code: "TJ", name: "Тоҷикистон" },
  { code: "TZ", name: "Tanzania" },
  { code: "TC", name: "Turks and Caicos Islands" },
  { code: "TR", name: "Türkiye" },
  { code: "TG", name: "Togo" },
  { code: "TK", name: "Tokelau" },
  { code: "TO", name: "Tonga" },
  { code: "TM", name: "Türkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "TN", name: "تونس" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "PA", name: "Panamá" },
  { code: "PY", name: "Paraguay" },
  { code: "PK", name: "پاکستان" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PW", name: "Belau" },
  { code: "PS", name: "Palestinian Territories" },
  { code: "FO", name: "Faroe Islands" },
  { code: "PE", name: "Perú" },
  { code: "PT", name: "Portugal" },
  { code: "FK", name: "Falkland Islands" },
  { code: "PL", name: "Polska" },
  { code: "PR", name: "Puerto Rico" },
  { code: "FR", name: "France" },
  { code: "GF", name: "French Guiana" },
  { code: "TF", name: "French Southern Territories" },
  { code: "PF", name: "French Polynesia" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Suomi" },
  { code: "PH", name: "Pilipinas" },
  { code: "PN", name: "Pitcairn" },
  { code: "HM", name: "Heard Island and McDonald Islands" },
  { code: "HU", name: "Magyarország" },
  { code: "HK", name: "Hong Kong" },
];
